"""Generate deterministic Godot boss resources from versioned JSON manifests.

Run from the project root:

    python assets/source/create_boss.py
    python assets/source/create_boss.py --check
    python assets/source/create_boss.py path/to/boss.json

``--all`` explicitly selects every non-template manifest. ``--scaffold`` may
create the declared generic controller script and scene when they do not exist.
Asset recipes are never run unless ``--build-asset`` is supplied.
"""

from __future__ import annotations

import argparse
import copy
import json
import math
import os
import re
import shutil
import subprocess
import sys
from dataclasses import dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Iterable


ROOT = Path(__file__).resolve().parents[2]
MANIFEST_DIR = ROOT / "assets/runtime/bosses/manifests"
DEFINITION_DIR = ROOT / "game/enemies/boss/definitions"
SPEC_DIR = ROOT / "game/enemies/boss/generated"
CATALOG = ROOT / "game/enemies/boss_catalog.gd"
DEFINITION_SCRIPT = "res://game/enemies/boss/boss_definition.gd"
TEMPLATE_NAME = "boss_template.json"
GENERATED_HEADER = (
    "# Generated by assets/source/create_boss.py. Do not hand-edit."
)
GENERATED_RESOURCE_HEADER = (
    "; Generated by assets/source/create_boss.py. Do not hand-edit."
)

ID_RE = re.compile(r"^[a-z][a-z0-9_]*$")
CLASS_RE = re.compile(r"^[A-Z][A-Za-z0-9]*$")
HEX_COLOR_RE = re.compile(r"^#?[0-9a-fA-F]{6}(?:[0-9a-fA-F]{2})?$")
CUSTOM_NAME_RE = re.compile(r"^custom:[a-z][a-z0-9_]*$")

GENERIC_BEHAVIORS = {
    "idle",
    "chase",
    "melee",
    "projectile",
    "area",
    "charge",
    "fly",
}
REGISTERED_PRETRIGGERS = {
    "arena_entry",
    "desert_flyby",
    "caldera_run",
}
CONTROLLER_MODES = {"custom", "generic"}
LOCATION_MODES = {"planet_surface", "world_space"}
DISTANCE_MODES = {"surface_arc", "euclidean"}
COLLISION_SHAPES = {"sphere", "capsule", "box"}


@dataclass(frozen=True)
class BossManifest:
    path: Path
    data: dict[str, Any]

    @property
    def boss_id(self) -> str:
        return str(self.data["id"])


def _unique_object(pairs: list[tuple[str, Any]]) -> dict[str, Any]:
    result: dict[str, Any] = {}
    for key, value in pairs:
        if key in result:
            raise ValueError(f"duplicate JSON key: {key!r}")
        result[key] = value
    return result


def read_json(path: Path) -> dict[str, Any]:
    try:
        value = json.loads(
            path.read_text(encoding="utf-8"),
            object_pairs_hook=_unique_object,
        )
    except FileNotFoundError as exc:
        raise ValueError(f"manifest does not exist: {_relative(path)}") from exc
    except (OSError, json.JSONDecodeError) as exc:
        raise ValueError(f"cannot read {_relative(path)}: {exc}") from exc
    if not isinstance(value, dict):
        raise ValueError(f"{_relative(path)}: manifest root must be an object")
    return value


def _relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(ROOT).as_posix()
    except (OSError, ValueError):
        return str(path)


def _check_keys(
    value: dict[str, Any],
    *,
    required: Iterable[str],
    allowed: Iterable[str],
    label: str,
) -> None:
    required_set = set(required)
    allowed_set = set(allowed)
    missing = sorted(required_set.difference(value))
    if missing:
        raise ValueError(f"{label}: missing {', '.join(missing)}")
    unknown = sorted(set(value).difference(allowed_set))
    if unknown:
        raise ValueError(f"{label}: unknown field(s) {', '.join(unknown)}")


def _required_object(value: Any, label: str) -> dict[str, Any]:
    if not isinstance(value, dict):
        raise ValueError(f"{label} must be an object")
    return value


def _required_list(value: Any, label: str) -> list[Any]:
    if not isinstance(value, list):
        raise ValueError(f"{label} must be an array")
    return value


def _required_string(value: Any, label: str) -> str:
    if not isinstance(value, str) or not value.strip():
        raise ValueError(f"{label} must be a non-empty string")
    return value


def _finite_number(value: Any, label: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{label} must be a finite number")
    result = float(value)
    if not math.isfinite(result):
        raise ValueError(f"{label} must be a finite number")
    return result


def _positive_number(value: Any, label: str) -> float:
    result = _finite_number(value, label)
    if result <= 0.0:
        raise ValueError(f"{label} must be greater than zero")
    return result


def _vector3(value: Any, label: str, *, positive: bool = False) -> list[float]:
    row = _required_list(value, label)
    if len(row) != 3:
        raise ValueError(f"{label} must contain exactly three numbers")
    result = [_finite_number(component, f"{label}[{index}]")
              for index, component in enumerate(row)]
    if positive and any(component <= 0.0 for component in result):
        raise ValueError(f"{label} dimensions must be greater than zero")
    return result


def _validate_json_safe(value: Any, label: str) -> None:
    if value is None or isinstance(value, (str, bool)):
        return
    if isinstance(value, int):
        if value < -(2**63) or value > 2**63 - 1:
            raise ValueError(f"{label} integer is outside Godot's 64-bit range")
        return
    if isinstance(value, float):
        if not math.isfinite(value):
            raise ValueError(f"{label} must not contain NaN or infinity")
        return
    if isinstance(value, list):
        for index, item in enumerate(value):
            _validate_json_safe(item, f"{label}[{index}]")
        return
    if isinstance(value, dict):
        for key, item in value.items():
            if not isinstance(key, str):
                raise ValueError(f"{label} object keys must be strings")
            _validate_json_safe(item, f"{label}.{key}")
        return
    raise ValueError(
        f"{label} contains unsupported JSON value {type(value).__name__}")


def _resource_file(
    value: Any,
    label: str,
    *,
    suffixes: tuple[str, ...] = (),
    allow_missing: bool = False,
) -> tuple[str, Path]:
    resource_path = _required_string(value, label).replace("\\", "/")
    if not resource_path.startswith("res://"):
        raise ValueError(f"{label} must be a res:// project path")
    relative = PurePosixPath(resource_path.removeprefix("res://"))
    if relative.is_absolute() or not relative.parts \
            or any(part in ("", ".", "..") for part in relative.parts):
        raise ValueError(f"{label} contains an invalid project path")
    disk_path = ROOT.joinpath(*relative.parts)
    if suffixes and disk_path.suffix.lower() not in suffixes:
        expected = ", ".join(suffixes)
        raise ValueError(f"{label} must end in one of: {expected}")
    if not allow_missing and not disk_path.is_file():
        raise ValueError(f"{label} is missing: {resource_path}")
    return resource_path, disk_path


def _animation_contract(
    value: Any,
    boss_id: str,
) -> tuple[dict[str, Any], set[str]]:
    animations = _required_object(value, f"{boss_id}.animations")
    if not animations:
        raise ValueError(f"{boss_id}.animations must not be empty")
    clips: set[str] = set()
    for role, mapping in animations.items():
        if not isinstance(role, str) or not ID_RE.fullmatch(role):
            raise ValueError(f"{boss_id}.animations has invalid role {role!r}")
        if isinstance(mapping, str):
            clips.add(_required_string(
                mapping, f"{boss_id}.animations.{role}"))
            continue
        subroles = _required_object(
            mapping, f"{boss_id}.animations.{role}")
        if not subroles:
            raise ValueError(
                f"{boss_id}.animations.{role} must not be empty")
        for subrole, clip in subroles.items():
            if not isinstance(subrole, str) or not ID_RE.fullmatch(subrole):
                raise ValueError(
                    f"{boss_id}.animations.{role} has invalid subrole "
                    f"{subrole!r}")
            clips.add(_required_string(
                clip, f"{boss_id}.animations.{role}.{subrole}"))
    rest = animations.get("rest")
    if not isinstance(rest, str) or not rest.strip():
        raise ValueError(f"{boss_id}: animations.rest must name a clip")
    return animations, clips


def _validate_moves(
    value: Any,
    boss_id: str,
    controller_mode: str,
    known_clips: set[str],
) -> list[dict[str, Any]]:
    moves = _required_list(value, f"{boss_id}.moves")
    if not moves:
        raise ValueError(f"{boss_id}.moves must not be empty")
    seen: set[str] = set()
    for index, raw_move in enumerate(moves):
        label = f"{boss_id}.moves[{index}]"
        move = _required_object(raw_move, label)
        _check_keys(
            move,
            required=("id", "behavior", "animations"),
            allowed=("id", "behavior", "animations", "parameters"),
            label=label,
        )
        move_id = _required_string(move["id"], f"{label}.id")
        if not ID_RE.fullmatch(move_id):
            raise ValueError(f"{label}.id is invalid: {move_id!r}")
        if move_id in seen:
            raise ValueError(f"{boss_id}: duplicate move id {move_id!r}")
        seen.add(move_id)

        behavior = _required_string(move["behavior"], f"{label}.behavior")
        built_in = behavior in GENERIC_BEHAVIORS
        custom = bool(CUSTOM_NAME_RE.fullmatch(behavior))
        if controller_mode == "generic" and not built_in:
            raise ValueError(
                f"{label}.behavior {behavior!r} is not registered for "
                "generic controllers")
        if controller_mode == "custom" and not (built_in or custom):
            raise ValueError(
                f"{label}.behavior must be built-in or use custom:<id>")

        mappings = _required_object(
            move["animations"], f"{label}.animations")
        if not mappings:
            raise ValueError(f"{label}.animations must not be empty")
        for stage, clip_value in mappings.items():
            if not isinstance(stage, str) or not ID_RE.fullmatch(stage):
                raise ValueError(
                    f"{label}.animations has invalid stage {stage!r}")
            clip = _required_string(
                clip_value, f"{label}.animations.{stage}")
            if clip not in known_clips:
                raise ValueError(
                    f"{label}.animations.{stage} maps unknown clip {clip!r}")
        if "parameters" in move:
            parameters = _required_object(
                move["parameters"], f"{label}.parameters")
            _validate_json_safe(parameters, f"{label}.parameters")
    return moves


def _validate_pretriggers(value: Any, boss_id: str) -> list[str]:
    raw_names = _required_list(value, f"{boss_id}.pretriggers")
    result: list[str] = []
    seen: set[str] = set()
    for index, raw_name in enumerate(raw_names):
        name = _required_string(
            raw_name, f"{boss_id}.pretriggers[{index}]")
        if name not in REGISTERED_PRETRIGGERS \
                and not CUSTOM_NAME_RE.fullmatch(name):
            raise ValueError(
                f"{boss_id}.pretriggers[{index}] has malformed or "
                f"unregistered name {name!r}")
        if name in seen:
            raise ValueError(f"{boss_id}: duplicate pretrigger {name!r}")
        seen.add(name)
        result.append(name)
    return result


def _validate_location(
    value: Any,
    boss_id: str,
    distance_mode: str,
) -> dict[str, Any]:
    location = _required_object(value, f"{boss_id}.location")
    mode = _required_string(location.get("mode"), f"{boss_id}.location.mode")
    if mode not in LOCATION_MODES:
        raise ValueError(f"{boss_id}.location.mode is invalid: {mode!r}")
    if mode == "planet_surface":
        _check_keys(
            location,
            required=("mode", "direction", "facing", "clearance"),
            allowed=("mode", "direction", "facing", "clearance"),
            label=f"{boss_id}.location",
        )
        direction = _vector3(
            location["direction"], f"{boss_id}.location.direction")
        length = math.sqrt(sum(component * component
                               for component in direction))
        if length <= 1.0e-6 or abs(length - 1.0) > 1.0e-3:
            raise ValueError(
                f"{boss_id}.location.direction must be a unit vector")
        _finite_number(location["facing"], f"{boss_id}.location.facing")
        clearance = _finite_number(
            location["clearance"], f"{boss_id}.location.clearance")
        if clearance < 0.0:
            raise ValueError(
                f"{boss_id}.location.clearance must not be negative")
        if distance_mode != "surface_arc":
            raise ValueError(
                f"{boss_id}: planet_surface requires surface_arc distance")
    else:
        _check_keys(
            location,
            required=("mode", "parent", "origin", "orientation"),
            allowed=("mode", "parent", "origin", "orientation"),
            label=f"{boss_id}.location",
        )
        _required_string(
            location["parent"], f"{boss_id}.location.parent")
        _vector3(location["origin"], f"{boss_id}.location.origin")
        _vector3(
            location["orientation"], f"{boss_id}.location.orientation")
        if distance_mode != "euclidean":
            raise ValueError(
                f"{boss_id}: world_space requires euclidean distance")
    return location


def _validate_waypoint(value: Any, boss_id: str) -> dict[str, Any]:
    waypoint = _required_object(value, f"{boss_id}.waypoint")
    _check_keys(
        waypoint,
        required=(
            "enabled",
            "title",
            "tint",
            "show_beyond",
            "aimed_beyond",
            "hide_beyond",
        ),
        allowed=(
            "enabled",
            "title",
            "tint",
            "show_beyond",
            "aimed_beyond",
            "hide_beyond",
        ),
        label=f"{boss_id}.waypoint",
    )
    if not isinstance(waypoint["enabled"], bool):
        raise ValueError(f"{boss_id}.waypoint.enabled must be a boolean")
    _required_string(waypoint["title"], f"{boss_id}.waypoint.title")
    tint = _required_string(waypoint["tint"], f"{boss_id}.waypoint.tint")
    if not HEX_COLOR_RE.fullmatch(tint):
        raise ValueError(f"{boss_id}.waypoint.tint must be RGB or RGBA hex")
    for key in ("show_beyond", "aimed_beyond", "hide_beyond"):
        amount = _finite_number(
            waypoint[key], f"{boss_id}.waypoint.{key}")
        if amount < 0.0:
            raise ValueError(
                f"{boss_id}.waypoint.{key} must not be negative")
    return waypoint


def validate_manifest(
    path: Path,
    *,
    allow_missing_controller: bool = False,
    allow_missing_runtime: bool = False,
) -> BossManifest:
    raw = read_json(path)
    data = copy.deepcopy(raw)
    if data.get("template") is True:
        raise ValueError(f"{_relative(path)} is a template, not a runtime boss")
    _check_keys(
        data,
        required=(
            "version",
            "id",
            "class_name",
            "display_name",
            "description",
            "asset",
            "controller",
            "health",
            "arena",
            "combat",
            "collision",
            "animations",
            "moves",
            "pretriggers",
            "location",
            "waypoint",
        ),
        allowed=(
            "version",
            "template",
            "id",
            "class_name",
            "display_name",
            "description",
            "asset",
            "controller",
            "health",
            "arena",
            "combat",
            "collision",
            "animations",
            "moves",
            "pretriggers",
            "location",
            "waypoint",
            "material",
            "tags",
            "extensions",
        ),
        label=_relative(path),
    )
    if isinstance(data["version"], bool) or data["version"] != 1:
        raise ValueError(f"{_relative(path)}: version must be 1")
    if "template" in data and not isinstance(data["template"], bool):
        raise ValueError(f"{_relative(path)}: template must be a boolean")

    boss_id = _required_string(data["id"], f"{_relative(path)}.id")
    if not ID_RE.fullmatch(boss_id):
        raise ValueError(f"{_relative(path)}: invalid boss id {boss_id!r}")
    class_name = _required_string(
        data["class_name"], f"{boss_id}.class_name")
    if not CLASS_RE.fullmatch(class_name):
        raise ValueError(f"{boss_id}: invalid class_name {class_name!r}")
    _required_string(data["display_name"], f"{boss_id}.display_name")
    _required_string(data["description"], f"{boss_id}.description")

    asset = _required_object(data["asset"], f"{boss_id}.asset")
    _check_keys(
        asset,
        required=("source",),
        allowed=("source", "runtime_glb", "builder"),
        label=f"{boss_id}.asset",
    )
    source, source_path = _resource_file(
        asset["source"],
        f"{boss_id}.asset.source",
        suffixes=(".blend", ".glb"),
    )
    if source_path.suffix.lower() == ".blend":
        if "runtime_glb" not in asset or "builder" not in asset:
            raise ValueError(
                f"{boss_id}: a .blend source requires asset.builder and "
                "asset.runtime_glb")
        runtime_glb, _runtime_path = _resource_file(
            asset["runtime_glb"],
            f"{boss_id}.asset.runtime_glb",
            suffixes=(".glb",),
            allow_missing=allow_missing_runtime,
        )
        builder, _builder_path = _resource_file(
            asset["builder"],
            f"{boss_id}.asset.builder",
            suffixes=(".py",),
        )
        asset["runtime_glb"] = runtime_glb
        asset["builder"] = builder
    else:
        runtime_value = asset.get("runtime_glb", source)
        runtime_glb, _runtime_path = _resource_file(
            runtime_value,
            f"{boss_id}.asset.runtime_glb",
            suffixes=(".glb",),
        )
        asset["runtime_glb"] = runtime_glb
        if "builder" in asset:
            builder, _builder_path = _resource_file(
                asset["builder"],
                f"{boss_id}.asset.builder",
                suffixes=(".py",),
            )
            asset["builder"] = builder
    asset["source"] = source

    controller = _required_object(
        data["controller"], f"{boss_id}.controller")
    _check_keys(
        controller,
        required=("mode", "scene", "script"),
        allowed=("mode", "scene", "script"),
        label=f"{boss_id}.controller",
    )
    controller_mode = _required_string(
        controller["mode"], f"{boss_id}.controller.mode")
    if controller_mode not in CONTROLLER_MODES:
        raise ValueError(
            f"{boss_id}.controller.mode is invalid: {controller_mode!r}")
    scene, _scene_path = _resource_file(
        controller["scene"],
        f"{boss_id}.controller.scene",
        suffixes=(".tscn",),
        allow_missing=allow_missing_controller and controller_mode == "generic",
    )
    script, _script_path = _resource_file(
        controller["script"],
        f"{boss_id}.controller.script",
        suffixes=(".gd",),
        allow_missing=allow_missing_controller and controller_mode == "generic",
    )
    controller["scene"] = scene
    controller["script"] = script

    _positive_number(data["health"], f"{boss_id}.health")

    arena = _required_object(data["arena"], f"{boss_id}.arena")
    _check_keys(
        arena,
        required=(
            "radius",
            "detection_radius",
            "reset_delay",
            "distance_mode",
        ),
        allowed=(
            "radius",
            "detection_radius",
            "reset_delay",
            "distance_mode",
        ),
        label=f"{boss_id}.arena",
    )
    _positive_number(arena["radius"], f"{boss_id}.arena.radius")
    _positive_number(
        arena["detection_radius"], f"{boss_id}.arena.detection_radius")
    _positive_number(
        arena["reset_delay"], f"{boss_id}.arena.reset_delay")
    distance_mode = _required_string(
        arena["distance_mode"], f"{boss_id}.arena.distance_mode")
    if distance_mode not in DISTANCE_MODES:
        raise ValueError(
            f"{boss_id}.arena.distance_mode is invalid: {distance_mode!r}")

    combat = _required_object(data["combat"], f"{boss_id}.combat")
    _check_keys(
        combat,
        required=("radius", "center_height"),
        allowed=("radius", "center_height"),
        label=f"{boss_id}.combat",
    )
    _positive_number(combat["radius"], f"{boss_id}.combat.radius")
    _positive_number(
        combat["center_height"], f"{boss_id}.combat.center_height")

    collision = _required_object(
        data["collision"], f"{boss_id}.collision")
    shape = _required_string(
        collision.get("shape"), f"{boss_id}.collision.shape")
    if shape not in COLLISION_SHAPES:
        raise ValueError(
            f"{boss_id}.collision.shape is invalid: {shape!r}")
    if shape == "sphere":
        _check_keys(
            collision,
            required=("shape", "radius", "offset"),
            allowed=("shape", "radius", "offset"),
            label=f"{boss_id}.collision",
        )
        _positive_number(
            collision["radius"], f"{boss_id}.collision.radius")
    elif shape == "capsule":
        _check_keys(
            collision,
            required=("shape", "radius", "height", "offset"),
            allowed=("shape", "radius", "height", "offset"),
            label=f"{boss_id}.collision",
        )
        _positive_number(
            collision["radius"], f"{boss_id}.collision.radius")
        _positive_number(
            collision["height"], f"{boss_id}.collision.height")
    else:
        _check_keys(
            collision,
            required=("shape", "size", "offset"),
            allowed=("shape", "size", "offset"),
            label=f"{boss_id}.collision",
        )
        _vector3(
            collision["size"], f"{boss_id}.collision.size", positive=True)
    _vector3(collision["offset"], f"{boss_id}.collision.offset")

    animations, clips = _animation_contract(data["animations"], boss_id)
    data["animations"] = animations
    data["moves"] = _validate_moves(
        data["moves"], boss_id, controller_mode, clips)
    data["pretriggers"] = _validate_pretriggers(
        data["pretriggers"], boss_id)
    data["location"] = _validate_location(
        data["location"], boss_id, distance_mode)
    data["waypoint"] = _validate_waypoint(data["waypoint"], boss_id)

    if "material" in data:
        material, _material_path = _resource_file(
            data["material"],
            f"{boss_id}.material",
            suffixes=(".tres", ".material"),
        )
        data["material"] = material

    tags = data.get("tags", [])
    tags = _required_list(tags, f"{boss_id}.tags")
    seen_tags: set[str] = set()
    for index, raw_tag in enumerate(tags):
        tag = _required_string(raw_tag, f"{boss_id}.tags[{index}]")
        if not ID_RE.fullmatch(tag):
            raise ValueError(f"{boss_id}: invalid tag {tag!r}")
        if tag in seen_tags:
            raise ValueError(f"{boss_id}: duplicate tag {tag!r}")
        seen_tags.add(tag)
    data["tags"] = tags

    extensions = data.get("extensions", {})
    data["extensions"] = _required_object(
        extensions, f"{boss_id}.extensions")
    return BossManifest(path.resolve(), data)


def discover_manifest_paths() -> list[Path]:
    if not MANIFEST_DIR.is_dir():
        raise ValueError(
            f"manifest directory is missing: {_relative(MANIFEST_DIR)}")
    result: list[Path] = []
    for path in sorted(MANIFEST_DIR.glob("*.json"), key=lambda item: item.name):
        raw = read_json(path)
        if path.name == TEMPLATE_NAME or raw.get("template") is True:
            continue
        result.append(path.resolve())
    if not result:
        raise ValueError("no runtime boss manifests found")
    return result


def resolve_manifest_arg(value: str) -> Path:
    if value.replace("\\", "/").startswith("res://"):
        _resource, path = _resource_file(
            value, "manifest", suffixes=(".json",))
        return path.resolve()
    path = Path(value)
    if not path.is_absolute():
        path = ROOT / path
    if path.suffix.lower() != ".json":
        raise ValueError(f"manifest must be a .json file: {value}")
    if not path.is_file():
        raise ValueError(f"manifest does not exist: {_relative(path)}")
    return path.resolve()


def load_manifests(
    paths: Iterable[Path],
    *,
    allow_missing_controller: bool = False,
    allow_missing_runtime: bool = False,
) -> list[BossManifest]:
    manifests = [
        validate_manifest(
            path,
            allow_missing_controller=allow_missing_controller,
            allow_missing_runtime=allow_missing_runtime,
        )
        for path in paths
    ]
    seen: dict[str, Path] = {}
    for manifest in manifests:
        previous = seen.get(manifest.boss_id)
        if previous is not None:
            raise ValueError(
                f"duplicate manifest id {manifest.boss_id!r}: "
                f"{_relative(previous)} and {_relative(manifest.path)}")
        seen[manifest.boss_id] = manifest.path
    return sorted(manifests, key=lambda item: item.boss_id)


def _godot_literal(value: Any) -> str:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        indent=2,
        allow_nan=False,
    )


def _float_literal(value: Any) -> str:
    number = float(value)
    if number == 0.0:
        number = 0.0
    result = repr(number)
    return result if "." in result or "e" in result.lower() else result + ".0"


def _packed_strings(values: list[str]) -> str:
    return "PackedStringArray({})".format(
        ", ".join(json.dumps(value, ensure_ascii=False) for value in values)
    )


def definition_text(manifest: BossManifest) -> str:
    entry = manifest.data
    ext_resources = [
        (
            "Script",
            DEFINITION_SCRIPT,
            "1_definition",
        ),
        (
            "PackedScene",
            entry["controller"]["scene"],
            "2_scene",
        ),
        (
            "Script",
            entry["controller"]["script"],
            "3_controller",
        ),
        (
            "PackedScene",
            entry["asset"]["runtime_glb"],
            "4_model",
        ),
    ]
    material_id = ""
    if entry.get("material"):
        material_id = "5_material"
        ext_resources.append(("Material", entry["material"], material_id))

    lines = [
        GENERATED_RESOURCE_HEADER,
        (
            "[gd_resource type=\"Resource\" script_class=\"BossDefinition\" "
            f"load_steps={len(ext_resources) + 1} format=3]"
        ),
        "",
    ]
    for kind, path, resource_id in ext_resources:
        lines.append(
            f"[ext_resource type={json.dumps(kind)} "
            f"path={json.dumps(path, ensure_ascii=False)} "
            f"id={json.dumps(resource_id)}]"
        )
    lines.extend(
        [
            "",
            "[resource]",
            "script = ExtResource(\"1_definition\")",
            f"boss_id = {json.dumps(entry['id'])}",
            f"boss_class_name = {json.dumps(entry['class_name'])}",
            f"display_name = {json.dumps(entry['display_name'], ensure_ascii=False)}",
            f"description = {json.dumps(entry['description'], ensure_ascii=False)}",
            f"controller_mode = &{json.dumps(entry['controller']['mode'])}",
            "boss_scene = ExtResource(\"2_scene\")",
            "controller_script = ExtResource(\"3_controller\")",
            "runtime_model = ExtResource(\"4_model\")",
            f"asset = {_godot_literal(entry['asset'])}",
            f"max_health = {_float_literal(entry['health'])}",
            f"arena_radius = {_float_literal(entry['arena']['radius'])}",
            (
                "detection_radius = "
                f"{_float_literal(entry['arena']['detection_radius'])}"
            ),
            f"reset_delay = {_float_literal(entry['arena']['reset_delay'])}",
            f"arena_distance_mode = &{json.dumps(entry['arena']['distance_mode'])}",
            f"combat = {_godot_literal(entry['combat'])}",
            f"collision = {_godot_literal(entry['collision'])}",
            f"animations = {_godot_literal(entry['animations'])}",
            f"moves = {_godot_literal(entry['moves'])}",
            f"pretriggers = {_packed_strings(entry['pretriggers'])}",
            f"location = {_godot_literal(entry['location'])}",
            f"waypoint = {_godot_literal(entry['waypoint'])}",
        ]
    )
    if material_id:
        lines.append(f"material_override = ExtResource({json.dumps(material_id)})")
    lines.extend(
        [
            f"tags = {_packed_strings(entry['tags'])}",
            f"extensions = {_godot_literal(entry['extensions'])}",
            "",
        ]
    )
    return "\n".join(lines)


def spec_text(manifest: BossManifest) -> str:
    entry = manifest.data
    location = copy.deepcopy(entry["location"])
    location["waypoint"] = copy.deepcopy(entry["waypoint"])
    return "\n".join(
        [
            GENERATED_HEADER,
            f"class_name {entry['class_name']}Spec",
            "extends RefCounted",
            "",
            f"const BOSS_ID := {json.dumps(entry['id'])}",
            f"const DISPLAY_NAME := {json.dumps(entry['display_name'], ensure_ascii=False)}",
            f"const MAX_HEALTH := {_float_literal(entry['health'])}",
            f"const ARENA_RADIUS := {_float_literal(entry['arena']['radius'])}",
            (
                "const DETECT_RADIUS := "
                f"{_float_literal(entry['arena']['detection_radius'])}"
            ),
            f"const RESET_DELAY := {_float_literal(entry['arena']['reset_delay'])}",
            f"const ANIMATIONS := {_godot_literal(entry['animations'])}",
            f"const MOVES := {_godot_literal(entry['moves'])}",
            f"const PRETRIGGERS := {_godot_literal(entry['pretriggers'])}",
            f"const LOCATION := {_godot_literal(location)}",
            f"const ASSET := {_godot_literal(entry['asset'])}",
            f"const EXTENSIONS := {_godot_literal(entry['extensions'])}",
            "",
        ]
    )


def catalog_text(manifests: list[BossManifest]) -> str:
    ids = ", ".join(json.dumps(manifest.boss_id) for manifest in manifests)
    paths = "\n".join(
        f"\t{json.dumps(manifest.boss_id)}: "
        f"{json.dumps('res://game/enemies/boss/definitions/' + manifest.boss_id + '.tres')},"
        for manifest in manifests
    )
    return f"""{GENERATED_HEADER}
class_name BossCatalog
extends RefCounted

const ORDER := [{ids}]
const PATHS := {{
{paths}
}}

static var _cache: Dictionary = {{}}


static func ids() -> PackedStringArray:
\treturn PackedStringArray(ORDER)


static func has(id: String) -> bool:
\treturn PATHS.has(id)


static func definition(id: String) -> BossDefinition:
\tif not PATHS.has(id):
\t\treturn null
\tif not _cache.has(id):
\t\tvar loaded := load(String(PATHS[id])) as BossDefinition
\t\tif loaded == null or not loaded.valid() or loaded.boss_id != id:
\t\t\tpush_error("Boss definition '%s' is invalid" % id)
\t\t\t_cache[id] = null
\t\telse:
\t\t\t_cache[id] = loaded
\treturn _cache[id] as BossDefinition
"""


def write_or_check(path: Path, content: str, check: bool) -> bool:
    current = path.read_text(encoding="utf-8") if path.exists() else None
    if current == content:
        return True
    if check:
        print(f"out of date: {_relative(path)}")
        return False
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8", newline="\n")
    print(f"wrote {_relative(path)}")
    return True


def clean_or_check_stale(
    directory: Path,
    pattern: str,
    expected: set[Path],
    check: bool,
) -> bool:
    if not directory.exists():
        return True
    ok = True
    for path in sorted(directory.glob(pattern), key=lambda item: item.name):
        if path.resolve() in expected:
            continue
        try:
            first_line = path.read_text(encoding="utf-8").splitlines()[0]
            generated = first_line in {
                GENERATED_HEADER,
                GENERATED_RESOURCE_HEADER,
            }
        except (OSError, IndexError):
            generated = False
        if not generated:
            print(f"kept non-generated file: {_relative(path)}")
            continue
        if check:
            print(f"stale generated file: {_relative(path)}")
            ok = False
        else:
            path.unlink()
            print(f"removed {_relative(path)}")
    return ok


def _scaffold_script(manifest: BossManifest) -> str:
    entry = manifest.data
    return f"""# Scaffolded by assets/source/create_boss.py. Safe to edit.
class_name {entry['class_name']}
extends BossController

const BOSS_ID := {json.dumps(entry['id'])}


func boss_id() -> String:
\treturn BOSS_ID


func definition() -> BossDefinition:
\treturn BossCatalog.definition(BOSS_ID)
"""


def _vector3_text(values: list[Any]) -> str:
    return "Vector3({})".format(
        ", ".join(_float_literal(value) for value in values)
    )


def _scaffold_scene(manifest: BossManifest) -> str:
    entry = manifest.data
    collision = entry["collision"]
    shape = collision["shape"]
    if shape == "sphere":
        shape_type = "SphereShape3D"
        shape_lines = [
            f"radius = {_float_literal(collision['radius'])}",
        ]
    elif shape == "capsule":
        shape_type = "CapsuleShape3D"
        shape_lines = [
            f"radius = {_float_literal(collision['radius'])}",
            f"height = {_float_literal(collision['height'])}",
        ]
    else:
        shape_type = "BoxShape3D"
        shape_lines = [
            f"size = {_vector3_text(collision['size'])}",
        ]
    shape_body = "\n".join(shape_lines)
    return f"""; Scaffolded by assets/source/create_boss.py. Safe to edit.
[gd_scene load_steps=4 format=3]

[ext_resource type="Script" path={json.dumps(entry['controller']['script'])} id="1_script"]
[ext_resource type="PackedScene" path={json.dumps(entry['asset']['runtime_glb'])} id="2_model"]

[sub_resource type={json.dumps(shape_type)} id="CollisionShape_boss"]
resource_local_to_scene = true
{shape_body}

[node name={json.dumps(entry['display_name'], ensure_ascii=False)} type="CharacterBody3D" groups=["bosses"]]
script = ExtResource("1_script")

[node name="CollisionShape3D" type="CollisionShape3D" parent="."]
position = {_vector3_text(collision['offset'])}
shape = SubResource("CollisionShape_boss")

[node name="Model" parent="." instance=ExtResource("2_model")]
"""


def _write_scaffold_if_absent(path: Path, content: str) -> None:
    if path.exists():
        print(f"kept existing scaffold: {_relative(path)}")
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    try:
        with path.open("x", encoding="utf-8", newline="\n") as handle:
            handle.write(content)
    except FileExistsError:
        print(f"kept existing scaffold: {_relative(path)}")
        return
    print(f"scaffolded {_relative(path)}")


def scaffold(manifest: BossManifest) -> None:
    entry = manifest.data
    if entry["controller"]["mode"] != "generic":
        print(f"skipped custom controller scaffold: {manifest.boss_id}")
        return
    expected_script = (
        f"res://game/enemies/{manifest.boss_id}/{manifest.boss_id}.gd"
    )
    expected_scene = (
        f"res://game/enemies/{manifest.boss_id}/{manifest.boss_id}.tscn"
    )
    if entry["controller"]["script"] != expected_script \
            or entry["controller"]["scene"] != expected_scene:
        raise ValueError(
            f"{manifest.boss_id}: generic scaffolds must use "
            f"{expected_script} and {expected_scene}")
    _script_resource, script_path = _resource_file(
        expected_script,
        f"{manifest.boss_id}.controller.script",
        suffixes=(".gd",),
        allow_missing=True,
    )
    _scene_resource, scene_path = _resource_file(
        expected_scene,
        f"{manifest.boss_id}.controller.scene",
        suffixes=(".tscn",),
        allow_missing=True,
    )
    _write_scaffold_if_absent(script_path, _scaffold_script(manifest))
    _write_scaffold_if_absent(scene_path, _scaffold_scene(manifest))


def blender_executable() -> str:
    configured = os.environ.get("BLENDER", "").strip().strip("\"")
    if configured:
        configured_path = Path(configured)
        if configured_path.is_file():
            return str(configured_path)
        located = shutil.which(configured)
        if located:
            return located
        raise ValueError(f"BLENDER does not name an executable: {configured}")
    located = shutil.which("blender") or shutil.which("blender.exe")
    if located:
        return located
    raise ValueError(
        "Blender was requested but not found; set BLENDER or add blender "
        "to PATH")


def build_assets(manifests: list[BossManifest]) -> None:
    recipes = [
        manifest for manifest in manifests
        if Path(manifest.data["asset"]["source"]).suffix.lower() == ".blend"
    ]
    if not recipes:
        print("no .blend assets selected for building")
        return
    blender = blender_executable()
    for manifest in recipes:
        _builder_resource, builder_path = _resource_file(
            manifest.data["asset"]["builder"],
            f"{manifest.boss_id}.asset.builder",
            suffixes=(".py",),
        )
        print(f"building asset: {manifest.boss_id}")
        try:
            subprocess.run(
                [
                    blender,
                    "--background",
                    "--factory-startup",
                    "--python",
                    str(builder_path),
                ],
                cwd=ROOT,
                check=True,
            )
        except subprocess.CalledProcessError as exc:
            raise ValueError(
                f"{manifest.boss_id}: Blender builder failed with "
                f"exit code {exc.returncode}") from exc


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Generate versioned boss resources and catalog")
    parser.add_argument(
        "manifests",
        nargs="*",
        help="optional individual manifest paths (defaults to all)",
    )
    parser.add_argument(
        "--all",
        action="store_true",
        help="explicitly generate every non-template runtime manifest",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="report generated drift without writing",
    )
    parser.add_argument(
        "--scaffold",
        action="store_true",
        help="create missing generic controller script/scene scaffolds",
    )
    parser.add_argument(
        "--build-asset",
        action="store_true",
        help="explicitly run selected .blend asset builders",
    )
    argv = sys.argv[sys.argv.index("--") + 1:] if "--" in sys.argv \
        else sys.argv[1:]
    args = parser.parse_args(argv)
    if args.all and args.manifests:
        parser.error("--all cannot be combined with individual manifests")
    if args.check and args.scaffold:
        parser.error("--check cannot be combined with --scaffold")
    if args.check and args.build_asset:
        parser.error("--check cannot be combined with --build-asset")
    return args


def run(args: argparse.Namespace) -> bool:
    default_paths = discover_manifest_paths()
    selected_paths = (
        [resolve_manifest_arg(value) for value in args.manifests]
        if args.manifests else default_paths
    )
    full_generation = not args.manifests

    catalog_paths = list(default_paths)
    known_paths = {path.resolve() for path in catalog_paths}
    for path in selected_paths:
        if path.resolve() not in known_paths:
            catalog_paths.append(path.resolve())
            known_paths.add(path.resolve())

    catalog_manifests = load_manifests(
        catalog_paths,
        allow_missing_controller=args.scaffold,
        allow_missing_runtime=args.build_asset,
    )
    selected_ids = {
        validate_manifest(
            path,
            allow_missing_controller=args.scaffold,
            allow_missing_runtime=args.build_asset,
        ).boss_id
        for path in selected_paths
    }
    selected = [
        manifest for manifest in catalog_manifests
        if manifest.boss_id in selected_ids
    ]
    if len(selected) != len(selected_ids):
        raise ValueError("selected manifest set could not be resolved")

    if args.scaffold:
        for manifest in selected:
            scaffold(manifest)
    if args.build_asset:
        build_assets(selected)

    # Revalidate after optional mutations so generated output never records a
    # scaffold or runtime model that failed to materialize.
    if args.scaffold or args.build_asset:
        catalog_manifests = load_manifests(catalog_paths)
        selected = [
            manifest for manifest in catalog_manifests
            if manifest.boss_id in selected_ids
        ]

    ok = True
    expected_definitions: set[Path] = set()
    expected_specs: set[Path] = set()
    for manifest in catalog_manifests:
        expected_definitions.add(
            (DEFINITION_DIR / f"{manifest.boss_id}.tres").resolve())
        expected_specs.add(
            (SPEC_DIR / f"{manifest.boss_id}_spec.gd").resolve())
    for manifest in selected:
        definition_path = DEFINITION_DIR / f"{manifest.boss_id}.tres"
        spec_path = SPEC_DIR / f"{manifest.boss_id}_spec.gd"
        ok = write_or_check(
            definition_path, definition_text(manifest), args.check) and ok
        ok = write_or_check(
            spec_path, spec_text(manifest), args.check) and ok
    ok = write_or_check(
        CATALOG, catalog_text(catalog_manifests), args.check) and ok

    if full_generation:
        ok = clean_or_check_stale(
            DEFINITION_DIR,
            "*.tres",
            expected_definitions,
            args.check,
        ) and ok
        ok = clean_or_check_stale(
            SPEC_DIR,
            "*_spec.gd",
            expected_specs,
            args.check,
        ) and ok
    return ok


def main() -> int:
    try:
        args = parse_args()
        return 0 if run(args) else 1
    except ValueError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
