# Generated by assets/source/create_boss.py. Do not hand-edit.
class_name BossCatalog
extends RefCounted

const ORDER := ["bigfoot", "sandworm", "volcanoronomous"]
const PATHS := {
	"bigfoot": "res://game/enemies/boss/definitions/bigfoot.tres",
	"sandworm": "res://game/enemies/boss/definitions/sandworm.tres",
	"volcanoronomous": "res://game/enemies/boss/definitions/volcanoronomous.tres",
}

static var _cache: Dictionary = {}


static func ids() -> PackedStringArray:
	return PackedStringArray(ORDER)


static func has(id: String) -> bool:
	return PATHS.has(id)


static func definition(id: String) -> BossDefinition:
	if not PATHS.has(id):
		return null
	if not _cache.has(id):
		var loaded := load(String(PATHS[id])) as BossDefinition
		if loaded == null or not loaded.valid() or loaded.boss_id != id:
			push_error("Boss definition '%s' is invalid" % id)
			_cache[id] = null
		else:
			_cache[id] = loaded
	return _cache[id] as BossDefinition
