# Generated by assets/source/build_ability_catalog.py. Do not hand-edit.
class_name AbilityCatalog
extends RefCounted

const ORDER := ["laser_eyes", "meteor_punch", "starfire", "grapple", "nuke", "lasso", "wall", "nausicaa", "poke_ball", "hero_punch", "building", "settlement_launcher"]
const PATHS := {
	"laser_eyes": "res://game/abilities/definitions/laser_eyes.tres",
	"meteor_punch": "res://game/abilities/definitions/meteor_punch.tres",
	"starfire": "res://game/abilities/definitions/starfire.tres",
	"grapple": "res://game/abilities/definitions/grapple.tres",
	"nuke": "res://game/abilities/definitions/nuke.tres",
	"lasso": "res://game/abilities/definitions/lasso.tres",
	"wall": "res://game/abilities/definitions/wall.tres",
	"nausicaa": "res://game/abilities/definitions/nausicaa.tres",
	"poke_ball": "res://game/abilities/definitions/poke_ball.tres",
	"hero_punch": "res://game/abilities/definitions/hero_punch.tres",
	"building": "res://game/abilities/definitions/building.tres",
	"settlement_launcher": "res://game/abilities/definitions/settlement_launcher.tres",
}

static var _cache: Dictionary = {}


static func ids() -> PackedStringArray:
	return PackedStringArray(ORDER)


static func has(id: String) -> bool:
	return PATHS.has(id)


static func definition(id: String) -> AbilityDefinition:
	if not PATHS.has(id):
		return null
	if not _cache.has(id):
		var loaded := load(String(PATHS[id])) as AbilityDefinition
		if loaded == null or not loaded.valid() or loaded.ability_id != id:
			push_error("Ability definition '%s' is invalid" % id)
			_cache[id] = null
		else:
			_cache[id] = loaded
	return _cache[id] as AbilityDefinition
